### ISSUE TITLE
PatMe should(?) use Dalamud's general channel

### ISSUE THREAD

**Issue by shaver** [MgAl2O4/PatMeDalamud#4]
That's what the developer of Tidy Chat said here when I reported that it was suppressing the /patme output:

https://github.com/NadyaNayme/TidyChat/issues/51

Hope this is helpful!

**Comment by MgAl2O4** [comment]
Tidy Chat is killing a lot of chat types by design, that what it's supposed to do. System channel is especially heavily affected, and that's where PatMe outputs its texts. There's no "general channel", unless they mean Say channel, which is not appropriate for my counter outputs. 

Can switch to something like Notice (idk, server info?) or Echo (macro output) and maybe it won't collide.

**Comment by NadyaNayme** [comment]
> Tidy Chat is killing a lot of chat types by design, that what it's supposed to do. System channel is especially heavily affected, and that's where PatMe outputs its texts. There's no "general channel", unless they mean Say channel, which is not appropriate for my counter outputs.
> 
> Can switch to something like Notice (idk, server info?) or Echo (macro output) and maybe it won't collide.

You can (and probably should) use `PluginInterface.GeneralChatType` which gets Dalamud's General Chat setting - which is set to `Debug` by default but can be set to go to pretty much any chat channel. This is what most plugins do and Tidy Chat does not filter _anything_ that sends to Debug since 100% of Debug channel messages are Dalamud or Dalamud Plugins as that is the only way to send anything to that channel - and at that point it isn't Tidy Chat's job to filter any plugin messages but the responsibility of the plugin to provide a way to disable its own messaging if a user doesn't want to see it.

This also lets users control where their plugin messages go in their chat tabs. By setting a non-Debug channel it lets them filter them into a specific tab group or if they use Chat2 they can filter Debug-channel messages into their own tab.

![image](https://user-images.githubusercontent.com/4567166/171045694-c8926a0e-9b46-4e42-a55c-a836e53a7523.png)


![image](https://user-images.githubusercontent.com/4567166/171045194-303da553-055b-4fdc-bc2a-3bc02e84e9f4.png)
